name: GitHub Pages Deployment

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: production
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'

    - name: Cache node_modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        
